FROM openjdk:11
EXPOSE 9099
WORKDIR /myapp
COPY /target/SportsAcademy-0.0.1-SNAPSHOT.jar /myapp/SportsAcademy-0.0.1-SNAPSHOT.jar
#ADD /target/bhar20293715img.jar bhar20293715img.jar
ENTRYPOINT ["java", "-jar", "SportsAcademy-0.0.1-SNAPSHOT.jar"]
